name: Deploy App to DEV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Logging
        run: |
          echo "Event: '${{ github.event_name }}'"
          echo "Branch ref: '${{ github.ref }}'"
          echo "Commit hash: '${{ github.sha }}'"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Source Branch: '${{ github.event.pull_request.head.ref }}'"
            echo "Target Branch: '${{ github.event.pull_request.base.ref }}'"
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base /family-budget-ui/dev
        env:
          VITE_APP_TEST_VAR: dev
          VITE_BE_REST_BASE_URL: ${{ secrets.BE_REST_BASE_URL_DEV }}

      - name: Deploy to GitHub Pages (dev)
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: dist
          target-folder: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Deploy to DEV"
