name: Deploy App to PROD

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Logging
        run: |
          echo "Event: '${{ github.event_name }}'"
          echo "Branch ref: '${{ github.ref }}'"
          echo "Commit hash: '${{ github.sha }}'"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Source Branch: '${{ github.event.pull_request.head.ref }}'"
            echo "Target Branch: '${{ github.event.pull_request.base.ref }}'"
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

#      - name: Update homepage in package.json
#        run: |
#          echo "Updating homepage to /prod"
#          sed -i "s|\"homepage\": \".*\"|\"homepage\": \"https://maestrokd.github.io/family-budget-ui/prod\"|" package.json

      - name: Build
        run: npm run build

#      - name: Deploy to GitHub Pages (prod)
#        uses: JamesIves/github-pages-deploy-action@v4.7.3
#        with:
#          folder: dist
##          target-folder: prod
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: "chore: Deploy to PROD"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
#          destination_dir: 'prdev' # Subdirectory for development
